<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>

    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>

    <AssemblyName>DiskMonitor</AssemblyName>
    <RootNamespace>DiskMonitor</RootNamespace>
    <ApplicationIcon>DiskMonitor.ico</ApplicationIcon>

    <PlatformTarget>AnyCPU</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>

    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>

    <Product>DiskMonitor</Product>
    <Company>DgLogiQ</Company>
    <Version>1.0.3</Version>
    <AssemblyVersion>1.0.3.0</AssemblyVersion>
    <FileVersion>1.0.3.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48"
                      Version="1.0.3"
                      PrivateAssets="All" />
  </ItemGroup>

</Project>
